
DROP TABLE IF EXISTS Resides ;
DROP TABLE IF EXISTS Folk_Phone ; 
DROP TABLE IF EXISTS Folk_Email ;
DROP TABLE IF EXISTS Judge ;
DROP TABLE IF EXISTS Clerk ;
DROP TABLE IF EXISTS Administrator  ;
DROP TABLE IF EXISTS monitors  ;
DROP TABLE IF EXISTS Voting_Registry;
DROP TABLE IF EXISTS VC_Operating_periods ;
DROP TABLE IF EXISTS Scheduled ;
DROP TABLE IF EXISTS Cast_Vote;
DROP TABLE IF EXISTS Ballots;
DROP TABLE IF EXISTS Voting_Center ;
DROP TABLE IF EXISTS Residence;
DROP TABLE IF EXISTS Election_Staff ;
DROP TABLE IF EXISTS Folk;
DROP TABLE IF EXISTS Place;
