#USED TO TEST TRANSACTION
#UPDATE Ballots SET start_at = '2022-09-11', end_at = '2022-10-21' WHERE Ballot_ID = 1189641421;


#THIS IS THE QUERY FOR Q9-- NOTE: IT WORKS
#WITH FOLK_ADDRESS AS (SELECT DISTINCT ID, x_coords AS ID_X, Y_coords AS ID_Y FROM (Voting_Registry NATURAL INNER JOIN Folk) NATURAL JOIN Place WHERE ID = 861021530),
#VC_ADDRESS AS(SELECT DISTINCT Unique_Acronym, x_coords, Y_coords FROM (Voting_Registry NATURAL INNER JOIN Voting_Center) NATURAL JOIN VC_Operating_periods NATURAL JOIN Place 
#WHERE '2022-9-15' between start_at and end_at ),
#DISTANCE AS (SELECT DISTINCT ID, Unique_Acronym, SQRT(POWER((x_coords-ID_X),2) +POWER((y_coords-ID_Y),2)) AS DISTANCE_TO_VC FROM FOLK_ADDRESS NATURAL INNER JOIN VC_ADDRESS)
#SELECT DISTINCT Unique_Acronym FROM DISTANCE WHERE (ID, DISTANCE_TO_VC) IN (SELECT ID, (MIN(DISTANCE_TO_VC)) FROM DISTANCE GROUP BY ID);

